# Generated by Django 5.2.13 on 2026-05-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_alter_encomienda_codigo_alter_encomienda_costo_envio_and_more'),
        ('envios', '0003_alter_encomienda_codigo_alter_encomienda_costo_envio_and_more'),
    ]

    operations = [
    ]
