# Generated by Django 5.2.13 on 2026-05-12 05:42

import django.core.validators
import envios.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_merge_20260512_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='peso_kg',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[envios.validators.validar_peso_positivo, django.core.validators.MinValueValidator(0.01, message='El peso mínimo es 0.01 kg')]),
        ),
    ]
