# Generated by Django 6.0.4 on 2026-04-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['codigo'], 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='ruta',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
