# Generated by Django 5.2.13 on 2026-05-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_alter_ruta_options_remove_ruta_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['origen', 'destino'], 'verbose_name': 'Ruta', 'verbose_name_plural': 'Rutas'},
        ),
        migrations.AddField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
